name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git gcc-arm-linux-gnueabihf

      - name: Cross-compile program
        run: |
          export CC=arm-linux-gnueabihf-gcc
          make
          mkdir -p bin
          cp bin/masscan ./bin/masscan

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan
