name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Upload
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t myprogram -f Dockerfile .
          docker run --name mycontainer myprogram  # Run the container to have access to its filesystem
          docker cp mycontainer:/app/bin/masscan bin/masscan  # Copy the binary from the container
          docker rm mycontainer  # Remove the temporary container
          echo "Binary file compiled and copied successfully."

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan
