name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install mingw -y
          # sudo ldd --version
          # sudo apt-get update
          # sudo apt-get install -y build-essential git libc6
          # sudo ldd --version

      - name: Cross-compile program
        run: |
          make CC=x86_64-w64-mingw32-gcc
          # git clone --depth 1 https://github.com/raspberrypi/tools.git /tmp/tools
          # export PATH=$PATH:/tmp/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin
          # make clean
          # make CC=arm-linux-gnueabihf-gcc

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan.exe
          # path: bin/masscan
