name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Upload
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t myprogram -f Dockerfile .
          docker cp $(docker ps -lq):/app/masscan .
          mv masscan bin/masscan  # Adjust the path if necessary
          echo "Binary file compiled and moved successfully."

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan
