name: Build and Upload Telex-Client

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  # We'll use an Ubuntu environment as MINGW and MSYS are not supported

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install necessary tools
      run: |
        which python
        which python2.7
        python -V
        ln -s /usr/bin/python2.7 /usr/bin/python
        python -V
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Set up environment and build telex-client
      run: |
        # sudo apt-get install python-is-python2
        # alias python=python2        
        git clone https://github.com/ewust/telex telex-git-clone
        mv telex-git-clone $HOME/telex
        curl "https://www.openssl.org/source/openssl-1.0.0d.tar.gz" -o $HOME/openssl-1.0.0d.tar.gz
        curl "http://web.archive.org/web/20181010160219/https://superb-dca2.dl.sourceforge.net/project/argtable/argtable/argtable-2.13/argtable2-13.tar.gz" -o $HOME/argtable2-13.tar.gz
        curl "https://monkey.org/~provos/libevent-2.0.12-stable.tar.gz" -o $HOME/libevent-2.0.12-stable.tar.gz        
        # mkdir $HOME/telex
        mkdir $HOME/telex/local
        export LDFLAGS="-L$HOME/telex/local/lib"
        export CFLAGS="-I$HOME/telex/local/include"
        cd $HOME/telex
        tar xf ../openssl-1.0.0d.tar.gz
        cd openssl-1.0.0d
        patch -p1 < ../telex-client/openssl-1.0.0d-telex.patch
        ./config no-shared no-hw no-asm --prefix=$HOME/telex/local/ --openssldir=$HOME/telex/local/
        make
        make install_sw
        cd $HOME/telex
        tar xf ../libevent-2.0.12-stable.tar.gz 
        cd libevent-2.0.12-stable
        ./configure --prefix=$HOME/telex/local --disable-shared
        make
        make install
        cd $HOME/telex
        tar xf ../argtable2-13.tar.gz
        cd argtable2-13
        ./configure --prefix=$HOME/telex/local
        make
        make install
        cd $HOME/telex/telex-client
        CC=gcc make -f Makefile.w32

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: telex-client
        path: $HOME/telex/telex-client/telex-client.exe
