name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Download Raspberry Pi toolchain
        run: |
          # wget https://github.com/raspberrypi/tools/archive/refs/tags/$(curl -s https://api.github.com/repos/raspberrypi/tools/tags | jq -r '.[0].name').tar.gz
          # tar xf $(curl -s https://api.github.com/repos/raspberrypi/tools/tags | jq -r '.[0].name').tar.gz
          sudo apt-get install gcc-arm-linux-gnueabihf

      - name: Cross-compile program
        run: |
          # export PATH=$PATH:$GITHUB_WORKSPACE/tools-$(curl -s https://api.github.com/repos/raspberrypi/tools/tags | jq -r '.[0].name')/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
          make clean  # Ensure clean build
          make CC=arm-linux-gnueabihf-gcc
          mkdir -p bin
          if [ ! -f bin/masscan ]; then
            cp masscan bin/masscan
          fi

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan
