name: Build and Upload Binary (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        uses: actions/setup-msys2@v1

      - name: Install Dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-python2 mingw-w64-x86_64-python3

      - name: Build Program
        run: |
          make

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: telex-client
          path: telex-client.exe  
