name: Compile and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/arm/v7 -t myprogram -f Dockerfile .

      - name: Cross-compile program
        run: |
          docker run --rm -v $(pwd):/workspace myprogram make clean
          docker run --rm -v $(pwd):/workspace myprogram make

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: masscan
          path: bin/masscan
