# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: |
        mkdir /tmp/go
        export GOPATH=/tmp/go
        env GOOS=windows GOARCH=amd64 go build -v -work ./...
        go env GOPATH
        ls -alRht /tmp/
        git status

    # - name: Test
    #   run: go test -v ./...
