name: Build and Upload hydra-windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Cygwin environment
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: |
            gcc-core,make,git,libssh-devel,libopenssl-devel,libidn-devel,libpcap-devel,libgcrypt-devel,libgpg-error-devel,libpq-devel,libsqlite3-devel,dos2unix,openssl,zip,


      - name: verify pkg
        run: |
          basic() {
              cygpath -w "$(pwd)"
              cygcheck -c gcc-core make git libssh-devel libopenssl-devel libidn-devel libpcap-devel libgcrypt-devel libgpg-error-devel libpq-devel libsqlite3-devel dos2unix openssl zip
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: dos2unix
        run: |
          basic() {
              cd ${GITHUB_WORKSPACE}
              dos2unix configure
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'


      - name: configure
        run: |
          basic() {
              cd ${GITHUB_WORKSPACE}
              mkdir $PWD/build
              ./configure --debug --prefix=$PWD/build
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'


      - name: make
        run: |
          basic() {
              cd ${GITHUB_WORKSPACE}
              export CC=gcc
              make 
              make install  
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'


      - name: find dll
        run: |
          basic() {
              find /cygdrive/c/tools/cygwin/ -type f -iname "*.dll"
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'


      - name: copy dll
        run: |
          basic() {
              cd ${GITHUB_WORKSPACE}/build
              find /cygdrive/c/tools/cygwin/ -type f -iname "*.dll" -exec cp {} . \;
              # find /cygdrive/c/tools/cygwin/ -type f -iname "*.dll" -print0 | xargs -0 -I {} cp {} .
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

      - name: zip
        run: |
          basic() {
              cd ${GITHUB_WORKSPACE}     
              chmod a=rwx build -R
              zip -r build.zip ./build
              ls -lh build.zip
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: |
            build.zip


