name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cygwin environment
        uses: egor-tensin/setup-cygwin@v3
        with:
          packages: |
            gcc-core
            make
            git
            libssh-devel
            libopenssl-devel
            libidn-devel
            libpcap-devel
            libgcrypt-devel
            libgpg-error-devel
            libmariadbclient-devel
            libpq-devel
            libsqlite3-devel

      - name: Run Cygwin Bash Shell
        shell: Cygwin {0}
        run: |
          ./configure
          make
          git status

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: hydra.exe
