name: Clone and Compress 

on:
  workflow_dispatch: 

jobs:
  clone_compress_upload:
    runs-on: ubuntu-latest

    steps:

    - name: Clone 
      run: |
        git clone https://github.com/barry-far/V2ray-Configs repo
        cd repo
        git submodule update --init --recursive 

    - name: Install 7z
      run: sudo apt-get install -y p7zip-full

    - name: Compress repository using 7z
      run: |
        7z a -t7z -m0=lzma2:d1024m -mx=9 -aoa -mfb=64 -md=32m -ms=on -mhe=on -pvomw -sdel compressed_repo.7z repo

    - name: Upload compressed repo
      uses: actions/upload-artifact@v3
      with:
        name: compressed-repo
        path: compressed_repo.7z
