name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cygwin
        run: |
          choco install cygwin --params "/InstallDir:C:\cygwin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          where refreshenv
          refreshenv

      - name: Download Cygwin setup-x86_64.exe
        run: |
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile C:\cygwin\setup-x86_64.exe
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Install Required Packages
        run: |
          C:\cygwin\bin\bash.exe -c "setup-x86_64.exe -h "
          C:\cygwin\bin\bash.exe -c "setup-x86_64.exe -q -P gcc-core,make,git,libssh-devel,libopenssl-devel,libidn-devel,libpcap-devel,libgcrypt-devel,libgpg-error-devel,libmariadbclient-devel,libpq-devel,libsqlite3-devel"

      - name: Compile THC-Hydra
        run: |
          
          C:\cygwin\bin\bash.exe -c "ls -lht ./configure && ./configure && make"
          git status

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: hydra.exe
