name: Build and Upload THC-Hydra for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Cygwin
        run: |
          choco install cygwin -y --params "/InstallDir:C:\cygwin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Download Cygwin setup-x86_64.exe
        run: |
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile C:\cygwin\setup-x86_64.exe

      - name: Install Required Packages
        run: |
          C:\cygwin\setup-x86_64.exe -q -P gcc-core,make,git,libssh-devel,libopenssl-devel,libidn-devel,libpcap-devel,libgcrypt-devel,libgpg-error-devel,libmariadbclient-devel,libpq-devel,libsqlite3-devel,dos2unix

      - name: Convert Line Endings
        run: |
          # pwd
          # echo ${GITHUB_WORKSPACE}
          # cd ${GITHUB_WORKSPACE}
          # pwd
          # dir
          # C:\cygwin\bin\bash.exe --help
          C:\cygwin\bin\bash.exe -lc "cd /cygdrive/d/a/sanctioned/sanctioned && ls -alth && dos2unix configure && git status"

      - name: Compile THC-Hydra
        run: |
          # cd ${GITHUB_WORKSPACE} 
          # pwd
          C:\cygwin\bin\bash.exe -lc "cd /cygdrive/d/a/sanctioned/sanctioned && export CC=gcc && ./configure --debug --disable-xhydra --prefix=$PWD/build && make"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: $GITHUB_WORKSPACE/hydra.exe
