name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# permissions:
#   contents: write      

jobs:
  build:
    runs-on: windows-latest
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # - name: clone
      #   run: |
      #     git clone https://github.com/vanhauser-thc/thc-hydra.git

      # - name: delete
      #   run: |
      #     cd thc-hydra
      #     sudo rm .gitignore
      #     sudo rm -rf .github
      #     sudo rm -rf .git
      #     sudo chmod a=rwx * -R

      # - name: move
      #   run: |
      #     cd thc-hydra
      #     shopt -s dotglob
      #     sudo mv * ../
      #     shopt -u dotglob
      #     sudo ls -alht

      # - name: git
      #   run: |
      #     sudo ls -alht thc-hydra
      #     sudo rm -rf thc-hydra
      #     git config --global user.name 'vomw'
      #     git config --global user.email '22770640+vomw@users.noreply.github.com'
      #     git add .
      #     git commit -m "clone "
      #     git push


      - name: Install Cygwin
        run: |
          choco install cygwin --params "/InstallDir:C:\cygwin"
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Download Cygwin setup-x86_64.exe
        run: |
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile C:\cygwin\setup-x86_64.exe

      - name: Install Required Packages
        run: |
          C:\cygwin\setup-x86_64.exe -h 
          # C:\cygwin\setup-x86_64.exe -q -P gcc-core,make,git,libssh-devel,libopenssl-devel,libidn-devel,libpcap-devel,libgcrypt-devel,libgpg-error-devel,libmariadbclient-devel,libpq-devel,libsqlite3-devel 
          C:\cygwin\setup-x86_64.exe -q -P libssl-dev,libssh-dev,libidn11-dev,libpcre3-dev,libgtk2.0-dev,libmysqlclient-dev,libpq-dev,libsvn-dev,firebird-dev,libmemcached-dev,libgpg-error-dev,libgcrypt11-dev,libgcrypt20-dev

      - name: Configure 
        run: |
          # C:\cygwin\bin\bash.exe -lc "dos2unix --help"
          C:\cygwin\bin\bash.exe -lc "./configure && git status"



      - name: Make
        run: |
          C:\cygwin\bin\bash.exe -lc "make && git status"          
          # C:\cygwin\bin\bash.exe -c "dos2unix *"
          # C:\cygwin\bin\bash.exe -c "./configure --debug && make"
          # C:\cygwin\bin\bash.exe -c "git status"


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: C:\cygwin\home\runneradmin\thc-hydra\hydra.exe