name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install cross-compiling tools for ARM
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install ARM target for Rust
        run: rustup target add armv7-unknown-linux-gnueabihf

      - name: Build for ARM
        run: cargo build --target=armv7-unknown-linux-gnueabihf --release

      - name: Prepare release directory
        run: |
          mkdir encrypted-dns-arm
          cp target/armv7-unknown-linux-gnueabihf/release/encrypted-dns encrypted-dns-arm/
          cp README.md example-encrypted-dns.toml encrypted-dns-arm/

      - name: Create release archive
        run: tar cjf encrypted-dns_${{ github.ref_name }}_armv7.tar.bz2 encrypted-dns-arm/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-dns_${{ github.ref_name }}_armv7
          path: encrypted-dns_${{ github.ref_name }}_armv7.tar.bz2

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: encrypted-dns_${{ github.ref_name }}_armv7

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            encrypted-dns_${{ github.ref_name }}_armv7/encrypted-dns
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
