name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# permissions:
#   contents: write      

jobs:
  build:
    runs-on: windows-latest
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # - name: clone
      #   run: |
      #     git clone https://github.com/vanhauser-thc/thc-hydra.git

      # - name: delete
      #   run: |
      #     cd thc-hydra
      #     sudo rm .gitignore
      #     sudo rm -rf .github
      #     sudo rm -rf .git
      #     sudo chmod a=rwx * -R

      # - name: move
      #   run: |
      #     cd thc-hydra
      #     shopt -s dotglob
      #     sudo mv * ../
      #     shopt -u dotglob
      #     sudo ls -alht

      # - name: git
      #   run: |
      #     sudo ls -alht thc-hydra
      #     sudo rm -rf thc-hydra
      #     git config --global user.name 'vomw'
      #     git config --global user.email '22770640+vomw@users.noreply.github.com'
      #     git add .
      #     git commit -m "clone "
      #     git push


      - name: Set up Cygwin environment
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: |
            gcc-core
            make
            git
            libssh-devel
            libopenssl-devel
            libidn-devel
            libpcap-devel
            libgcrypt-devel
            libgpg-error-devel
            libmariadbclient-devel
            libpq-devel
            libsqlite3-devel



      - name: debug
        run: |
          dir
          pwd
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          dir
     

      # set Cygwin's bash as the shell to use:
      - name: Bash shell
        run: |
          # This is a real bash script!
          basic() {
              cd ${GITHUB_WORKSPACE}
              pwd
              ls -alht
              git config core.autocrlf true
              dos2unix *
              dos2unix .*
              git status
              # ./configure
              git config --global user.name 'vomw'
              git config --global user.email '22770640+vomw@users.noreply.github.com'
              git status
              git add .
              git commit -m "configure 2 "
              git push
              make
              git status
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'





      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hydra-windows
          path: hydra.exe