
name: vue
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install
        run: |
          npm --help
          # npm install
          # npm run serve
          # CI=false npm install

      - name: npm run build
        run: |
          npm run build

      - name: npm run test
        run: |
          npm run test

      - name: npm run lint
        run: |
          npm run lint

      - name: check files
        run: |
          git status
          ls -alht

      # - name: Setup Pages  # Configures pages for deployment.
      #   id: pages
      #   uses: actions/configure-pages@v3

      # - name: Build with Jekyll  # Builds the application with Jekyll.
      #   uses: actions/jekyll-build-pages@v1
      #   with:
      #     source: ./dist/
      #     destination: ./_site

      - name: Upload page artifact 
        uses: actions/upload-pages-artifact@v2     

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            dist
            index.html
            
